<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\CriaCerto.BuildingBlocks.Infrastructure\CriaCerto.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\CriaCerto.Modules.Growth.Application\CriaCerto.Modules.Growth.Application.csproj" />
  </ItemGroup>

</Project>
