<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CriaCerto.Web.Client.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\CriaCerto.BuildingBlocks.Abstractions\CriaCerto.BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Modules\Breeding\CriaCerto.Modules.Breeding.Application\CriaCerto.Modules.Breeding.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Calving\CriaCerto.Modules.Calving.Application\CriaCerto.Modules.Calving.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Growth\CriaCerto.Modules.Growth.Application\CriaCerto.Modules.Growth.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Nutrition\CriaCerto.Modules.Nutrition.Application\CriaCerto.Modules.Nutrition.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Sanitary\CriaCerto.Modules.Sanitary.Application\CriaCerto.Modules.Sanitary.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Backoffice\CriaCerto.Modules.Backoffice.Application\CriaCerto.Modules.Backoffice.Application.csproj" />
    <ProjectReference Include="..\..\..\Modules\Analytics\CriaCerto.Modules.Analytics.Application\CriaCerto.Modules.Analytics.Application.csproj" />
  </ItemGroup>

</Project>
